### ISSUE TITLE
Java, Excercise 4 : custom handler not called for associations

### ISSUE THREAD

**Issue by dinurp** [SAP-samples/cloud-cap-walkthroughs#21]
At the end of the excercise 3 (https://github.com/SAP-samples/cloud-cap-walkthroughs/blob/master/exercises-java/exercise4/README.md) when I look at
/odata/v4/OrdersService/Orders?$expand=items 
populates the total for orders.

But if one tries
/odata/v4/OrdersService/OrderItems?$expand=parent
total for orders is not populated.

Isnt the event handler for READ called while navigating associations?

**Comment by chgeo** [comment]
@beckermarc can yoo answer this?

**Comment by beckermarc** [comment]
Events are only triggered on the target entity of the request. In case of `/odata/v4/OrdersService/OrderItems?$expand=parent` this is `OrderItems`.

This is also the reason why the netAmount calculation of order items is explicitly triggered, when an order is read: https://github.com/SAP-samples/cloud-cap-samples/blob/CAA160-final/bookstore/srv/src/main/java/com/sap/teched/cap/bookstore/handlers/OrdersService.java#L86

When implementing after read handlers you have to deal with the full complexity of the query. It is therefore usually a better practice to calculate such fields on create or update, instead of calculating them during read. We are going to release an updated sample application soon, where this best practice is also showed and followed.

More information about this can be found in our [documentation](https://cap.cloud.sap/docs/java/). [This part](https://cap.cloud.sap/docs/java/provisioning-api#crudevents) describes, that events are only triggered on the root / target entity.
